import type {
  AffiliateProduct,
  Brand,
  BrandBattle,
  Category,
  Company,
  SponsoredSlot,
} from "./types";

export const brands: Brand[] = [
  {
    id: "karcher",
    slug: "karcher",
    name: "Kärcher",
    tagline: "Профессиональная техника для клининга",
    accent: "#FFC800",
    focus: "technika",
    description:
      "Мировой лидер в производстве клининговой техники: экстракторы, парогенераторы, поломоечные машины. Официальный сервис и склад запчастей в Минске.",
    affiliateUrl: "https://www.karcher.by/",
  },
  {
    id: "dyson",
    slug: "dyson",
    name: "Dyson",
    tagline: "Технологии чистого воздуха",
    accent: "#6B4EFF",
    focus: "technika",
    description:
      "Беспроводные пылесосы и очистители воздуха премиум-класса — выбор клининговых компаний для деликатной уборки в дорогих интерьерах.",
    affiliateUrl: "https://www.21vek.by/dyson/",
  },
  {
    id: "bosch",
    slug: "bosch",
    name: "Bosch",
    tagline: "Надёжная техника для бизнеса",
    accent: "#EA0016",
    focus: "technika",
    description:
      "Промышленные пылесосы и электроинструмент Bosch Professional для клининга офисов и коммерческих помещений.",
    affiliateUrl: "https://www.bosch-professional.com/by/ru/",
  },
  {
    id: "ecolab",
    slug: "ecolab",
    name: "Ecolab",
    tagline: "Экологичная химия для клининга",
    accent: "#0074B7",
    focus: "himiya",
    description:
      "Гипоаллергенная профессиональная химия для дезинфекции и уборки — используется ведущими клининговыми компаниями Беларуси.",
    affiliateUrl: "https://www.ecolab.com/",
  },
  {
    id: "grass",
    slug: "grass",
    name: "Grass",
    tagline: "Химия для сложных загрязнений",
    accent: "#16A34A",
    focus: "himiya",
    description:
      "Средства от жира, пятен и монтажной пены. Оптовые поставки для клининговых компаний с доставкой по РБ.",
    affiliateUrl: "https://grass.by/",
  },
  {
    id: "vileda-pro",
    slug: "vileda-professional",
    name: "Vileda Professional",
    tagline: "Инвентарь для профессиональной уборки",
    accent: "#F97316",
    focus: "inventory",
    description:
      "Швабры, ведра с отжимом, микрофибра и системы уборки для клининговых бригад любого масштаба.",
    affiliateUrl: "https://www.vileda-professional.com/",
  },
  {
    id: "dreame",
    slug: "dreame",
    name: "Dreame",
    tagline: "Роботы-пылесосы нового поколения",
    accent: "#0EA5E9",
    focus: "technika",
    description:
      "Роботы-пылесосы с влажной уборкой для дома — рекомендация клинеров для поддержания чистоты между генеральными уборками.",
    affiliateUrl: "https://www.onliner.by/catalog/dreame",
  },
  {
    id: "kiehl",
    slug: "kiehl",
    name: "Kiehl",
    tagline: "Немецкая профессиональная химия для клининга",
    accent: "#0284C7",
    focus: "himiya",
    description:
      "Концентрированные средства для удаления застарелых пятен, затирок, полимерных покрытий и генеральной уборки.",
    affiliateUrl: "https://www.kiehl-group.com/",
  },
  {
    id: "prochem",
    slug: "prochem",
    name: "Prochem",
    tagline: "Мировой эталон химии для химчистки мягкой мебели",
    accent: "#D97706",
    focus: "himiya",
    description:
      "Профессиональные пятновыводители, нейтрализаторы запахов и экстракционные шампуни для клинеров и химчисток.",
    affiliateUrl: "https://www.prochem.co.uk/",
  },
];

export const categories: Category[] = [
  { id: "apartments", name: "Уборка квартир", icon: "Home", brandId: "dyson" },
  { id: "offices", name: "Уборка офисов", icon: "Building2", brandId: "bosch" },
  { id: "upholstery", name: "Химчистка мебели", icon: "Sofa", brandId: "ecolab" },
  { id: "windows", name: "Мытьё окон", icon: "AppWindow", brandId: "vileda-pro" },
  { id: "post-renovation", name: "Уборка после ремонта", icon: "HardHat", brandId: "karcher" },
  { id: "deep-cleaning", name: "Генеральная уборка", icon: "Sparkles", brandId: "karcher" },
];

// Реальные компании рынка клининга Минска. Партнёры платформы (promoted: true) — это открыто
// оплаченное размещение, которое НЕ влияет на органический рейтинг (baseRating/reviewCount).
// Компании без ratingSource: "google"/"yandex" — платформа честно не публикует рейтинг вместо
// того, чтобы его выдумывать (см. CompanyCard: бейдж "Рейтинг формируется"/"Рейтинг уточняется").
export const companies: Company[] = [
  {
    id: "spectrclean",
    slug: "spectrclean",
    name: "Спектр Клининг",
    categories: ["offices", "post-renovation", "deep-cleaning", "windows", "upholstery", "apartments"],
    city: "Минск",
    verified: true,
    promoted: false,
    equipment: ["karcher"],
    baseRating: 4.8,
    reviewCount: 12,
    ratingSource: "google",
    priceFrom: 6,
    priceUnit: "м²",
    coverImage: "https://picsum.photos/seed/spectrclean/800/600",
    description:
      "Профессиональный клининг для бизнеса и дома в Минске: регулярная уборка по договору, генеральная и послестроительная уборка. Специализация — пищевые производства, серверные, склады.",
    tags: ["Работает по договору", "7+ лет на рынке", "350+ клиентов"],
    websiteUrl: "https://spectrclean.by",
    phone: "+375 29 186-98-88",
    telegramUrl: "https://t.me/Spectr_Cleaning_Bot",
    email: "info@spectrclean.by",
    experienceYears: 7,
    guarantees: ["Фиксированная цена по договору"],
    recentReview: {
      author: "Ольга, HR-менеджер, IT-компания",
      text: "Работаем со «Спектр-Клининг» уже год. Всегда вовремя, чисто, никаких нареканий. Менеджер на связи, все вопросы решаются оперативно.",
      rating: 5,
    },
  },
  {
    id: "freshclean",
    slug: "freshclean",
    name: "FreshClean",
    categories: ["apartments", "offices", "post-renovation", "deep-cleaning"],
    city: "Минск",
    verified: true,
    promoted: false,
    baseRating: 4.5,
    reviewCount: 8,
    ratingSource: "yandex",
    priceFrom: 3,
    priceUnit: "м²",
    coverImage: "https://picsum.photos/seed/freshclean/800/600",
    description:
      "Уборка квартир, домов, офисов и коммерческой недвижимости по всей Беларуси. Итоговая стоимость рассчитывается индивидуально в зависимости от площади и степени загрязнения.",
    tags: ["Работает по всей Беларуси", "Индивидуальный расчёт стоимости"],
    websiteUrl: "https://freshclean.by",
    phone: "+375 25 525-76-10",
    email: "info@freshclean.by",
    experienceYears: 5,
  },
  {
    id: "kitt",
    slug: "chistiy-kit",
    name: "Чистый Кит (CleanWhale)",
    categories: ["apartments", "windows", "post-renovation", "upholstery"],
    city: "Минск",
    verified: false,
    promoted: false,
    baseRating: 0,
    reviewCount: 0,
    ratingSource: "unverified",
    priceFrom: 94.99,
    coverImage: "https://picsum.photos/seed/kitt/800/600",
    description:
      "Уборка квартир, мойка окон, химчистка и уборка после ремонта в Минске. Работает по системе онлайн-бронирования с выбором клинера; регулярная уборка обходится дешевле разовой.",
    tags: ["Онлайн-бронирование", "Скидки при регулярной уборке"],
    websiteUrl: "https://kitt.by",
  },
  {
    id: "cleanclean",
    slug: "clean-clean",
    name: "Clean.Clean",
    categories: ["apartments", "deep-cleaning", "post-renovation", "windows"],
    city: "Минск",
    verified: false,
    promoted: false,
    baseRating: 0,
    reviewCount: 0,
    ratingSource: "unverified",
    priceFrom: 100,
    coverImage: "https://picsum.photos/seed/cleanclean/800/600",
    description: "Уборка квартир, домов и офисов в Минске: от поддерживающей до генеральной уборки и уборки после стройки.",
    tags: ["Прозрачные тарифы", "Расчёт стоимости онлайн"],
    websiteUrl: "https://clean-clean.by",
  },
  {
    id: "freshroom",
    slug: "freshroom",
    name: "FreshRoom",
    categories: ["apartments", "post-renovation", "upholstery"],
    city: "Минск",
    address: "ул. Веры Хоружей, 29",
    verified: false,
    promoted: false,
    baseRating: 0,
    reviewCount: 0,
    ratingSource: "unverified",
    priceFrom: 85,
    coverImage: "https://picsum.photos/seed/freshroom/800/600",
    description:
      "Уборка квартир и домов в Минске силами клинеров-партнёров. Цены фиксированы для постоянных клиентов при уборке раз в неделю.",
    tags: ["Регулярная уборка", "Выезд день в день"],
    websiteUrl: "https://freshroom.by",
    phone: "+375 44 749-88-99",
    email: "info@freshroom.by",
  },
  {
    id: "skyclean",
    slug: "skyclean",
    name: "SkyClean",
    categories: ["apartments", "offices", "deep-cleaning", "post-renovation", "windows", "upholstery"],
    city: "Минск",
    verified: false,
    promoted: false,
    equipment: ["karcher", "vileda-pro"],
    baseRating: 0,
    reviewCount: 0,
    ratingSource: "unverified",
    priceFrom: 100,
    coverImage: "https://picsum.photos/seed/skyclean/800/600",
    description:
      "Уборка квартир, коттеджей и офисов в Минске и Минской области. Работа строго по предварительной записи, застрахованная ответственность.",
    tags: ["Минск и область", "Опыт более 10 лет", "Застрахованная ответственность"],
    websiteUrl: "https://skyclean.by",
    phone: "+375 29 66 33 555",
    email: "info@skyclean.by",
    experienceYears: 10,
  },
  {
    id: "sauber",
    slug: "sauber",
    name: "SAUBER GRUPPE",
    categories: ["offices", "post-renovation", "deep-cleaning", "windows", "upholstery"],
    city: "Минск",
    verified: false,
    promoted: false,
    baseRating: 4.6,
    reviewCount: 24,
    ratingSource: "google",
    priceFrom: 18,
    priceUnit: "окно",
    coverImage: "https://picsum.photos/seed/sauber/800/600",
    description:
      "Клининговая компания в Минске: уборка квартир и офисов, после ремонта, мойка окон и химчистка. Более 9 300 выполненных уборок с 2019 года.",
    tags: ["9300+ уборок с 2019 года", "Калькулятор цены на сайте"],
    websiteUrl: "https://sauber.space",
    phone: "+375 29 723-88-88",
    experienceYears: 6,
  },
];

// Честные цифры о самой платформе на старте — без завышения масштаба.
export const trustStats: Array<{ label: string; value: number; suffix?: string; decimals?: number }> = [
  { label: "компаний в каталоге Минска", value: companies.length },
  { label: "категорий услуг", value: categories.length },
  { label: "лет опыта у топ-партнёра", value: 7, suffix: "+" },
];

export const affiliateProducts: AffiliateProduct[] = [
  {
    id: "p1",
    slug: "karcher-puzzi-10-1",
    brandId: "karcher",
    name: "Kärcher Puzzi 10/1",
    image: "https://picsum.photos/seed/karcher-puzzi/600/450",
    category: "extractors",
    price: 2890,
    rating: 4.9,
    badge: "Выбор профи",
    pros: ["Экстракция за 1 проход", "Бак 10 л", "Для ковров и мебели"],
    affiliateUrl: "https://www.karcher.by/puzzi-10-1",
  },
  {
    id: "p2",
    slug: "grass-anti-fat",
    brandId: "grass",
    name: "Grass Universal Anti-Fat",
    image: "https://picsum.photos/seed/grass-antifat/600/450",
    category: "chemistry",
    price: 45,
    rating: 4.7,
    badge: "Хит продаж",
    pros: ["Удаляет жир и нагар", "Концентрат 1:200", "Экономичный расход"],
    affiliateUrl: "https://grass.by/universal-anti-fat",
  },
  {
    id: "p3",
    slug: "dreame-l10s-pro",
    brandId: "dreame",
    name: "Dreame L10s Pro",
    image: "https://picsum.photos/seed/dreame-l10s/600/450",
    category: "robots",
    price: 1690,
    rating: 4.6,
    badge: "Новинка",
    pros: ["Сухая и влажная уборка", "Самоочистка станции", "Умное картирование"],
    affiliateUrl: "https://www.onliner.by/catalog/dreame/l10s-pro",
  },
  {
    id: "p4",
    slug: "vileda-window-kit",
    brandId: "vileda-pro",
    name: "Vileda Professional WindowMaster",
    image: "https://picsum.photos/seed/vileda-window/600/450",
    category: "windows",
    price: 89,
    rating: 4.5,
    pros: ["Без разводов", "Телескопическая ручка до 3 м", "Быстрая замена насадок"],
    affiliateUrl: "https://www.vileda-professional.com/windowmaster",
  },
  {
    id: "p5",
    slug: "ecolab-oasis-pro",
    brandId: "ecolab",
    name: "Ecolab Oasis Pro 60",
    image: "https://picsum.photos/seed/ecolab-oasis/600/450",
    category: "chemistry",
    price: 62,
    rating: 4.8,
    pros: ["Гипоаллергенно", "Дезинфекция поверхностей", "Сертифицировано для соцобъектов"],
    affiliateUrl: "https://www.ecolab.com/oasis-pro-60",
  },
  {
    id: "p6",
    slug: "bosch-gas-18v",
    brandId: "bosch",
    name: "Bosch GAS 18V-10 L",
    image: "https://picsum.photos/seed/bosch-gas/600/450",
    category: "extractors",
    price: 780,
    rating: 4.7,
    pros: ["Аккумуляторный, без шнура", "Компактный корпус", "Для офисной уборки"],
    affiliateUrl: "https://www.bosch-professional.com/by/ru/gas-18v-10-l",
  },
  {
    id: "p7",
    slug: "dyson-v15-detect",
    brandId: "dyson",
    name: "Dyson V15 Detect",
    image: "https://picsum.photos/seed/dyson-v15/600/450",
    category: "robots",
    price: 2150,
    rating: 4.9,
    badge: "Выбор профи",
    pros: ["Лазерная подсветка пыли", "До 60 мин работы", "HEPA-фильтрация"],
    affiliateUrl: "https://www.21vek.by/dyson/v15-detect",
  },
];

export const sponsoredSlots: SponsoredSlot[] = [
  { categoryId: "apartments", brandId: "dyson", price: 1400, periodLabel: "Ноябрь 2026", impressions: 42000, clicks: 1850 },
  { categoryId: "offices", brandId: "bosch", price: 1200, periodLabel: "Ноябрь 2026", impressions: 27500, clicks: 980 },
  { categoryId: "upholstery", brandId: "ecolab", price: 950, periodLabel: "Ноябрь 2026", impressions: 15200, clicks: 640 },
  { categoryId: "windows", brandId: "vileda-pro", price: 800, periodLabel: "Ноябрь 2026", impressions: 11800, clicks: 410 },
  { categoryId: "post-renovation", brandId: "karcher", price: 1600, periodLabel: "Ноябрь 2026", impressions: 31000, clicks: 1420 },
  { categoryId: "deep-cleaning", brandId: "karcher", price: 1750, periodLabel: "Ноябрь 2026", impressions: 38700, clicks: 1690 },
];

export const brandBattles: BrandBattle[] = [
  {
    id: "b1",
    brandAId: "karcher",
    brandBId: "bosch",
    theme: "Экстракторы для химчистки",
    votesA: 612,
    votesB: 548,
    endsAt: Date.now() + 4 * 24 * 60 * 60 * 1000,
  },
  {
    id: "b2",
    brandAId: "grass",
    brandBId: "ecolab",
    theme: "Химия против жира и пятен",
    votesA: 389,
    votesB: 421,
    endsAt: Date.now() + 4 * 24 * 60 * 60 * 1000,
  },
  {
    id: "b3",
    brandAId: "dyson",
    brandBId: "dreame",
    theme: "Техника для дома клиентов",
    votesA: 705,
    votesB: 663,
    endsAt: Date.now() + 4 * 24 * 60 * 60 * 1000,
  },
];
